// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('welcome', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('welcome', async function() {
    await driver.get("http://localhost:7357/")
    await driver.findElement(By.css("[data-sel=\"title\"]")).click()
    assert(await driver.findElement(By.css("[data-sel=\"title\"]")).getText() == "Welcome")
    await driver.wait(until.elementIsVisible(await driver.findElement(By.css("[data-sel=\"list\"]"))), 30000)
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css("[data-sel=\"go\"]")).click()
    vars["win7086"] = await waitForWindow(2000)
  })
})
