name: Tests

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-firefox:latest
        ports:
          - "4444:4444"
        options: --shm-size="2g"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      - name: Install dependencies
        run: npm i

      - name: Install Side Runner
        run: npm install -g selenium-side-runner

      - name: Setup Geckodriver
        uses: browser-actions/setup-geckodriver@latest

      - name: Build
        run: npm run build

      - name: Start React app
        run: |
          npm start &

      - name: Wait for React app to be ready
        run: |
          npx wait-on http://localhost:3000

      - name: Run tests
        run: selenium-side-runner -s http://localhost:3000 test/test.side

