name: Tests

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: --shm-size="2g"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      - name: Install dependencies
        run: npm ci

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1.7.2

      - name: Install Driver
        uses: nanasess/setup-chromedriver@v2

      - name: Install Side Runner
        run: npm install -g selenium-side-runner

      - name: Build
        run: npm run build

      - name: Run tests
      run: selenium-side-runner --server http://localhost:4444/wd/hub -c "goog:chromeOptions.args=[--headless,--nogpu] browserName=chrome" test/test.side

