name: Tests

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Chrome
        uses: browser-actions/setup-chrome@v1.7.2

      - name: Driver
        uses: nanasess/setup-chromedriver@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      - name: Install dependencies
        run: npm ci

      - name: Install Side Runner
        run: npm install -g selenium-side-runner

      - name: Build
        run: npm run build

      - name: Run tests
        run: selenium-side-runner -c "goog:chromeOptions.args=[--headless,--nogpu] browserName=chrome" test/test.side

