name: Test
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:

  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: npm i

      - run: npm run test
