name: Tests

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: --shm-size="2g"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      - name: Install dependencies
        run: npm ci

      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable

      - name: Remove default Chromium
        run: sudo apt purge chromium-browser
        
      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser

      - name: Install Driver
        uses: nanasess/setup-chromedriver@v2

      - name: Install Side Runner
        run: npm install -g selenium-side-runner

      - name: Build
        run: npm run build

      - name: Run tests
        run: selenium-side-runner -c "goog:chromeOptions.args=[--headless,--nogpu] browserName=chrome" test/test.side

