name: Tests

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Chrome
        uses: browser-actions/setup-chrome@v1.7.2
    

      - name: Driver
        uses: nanasess/setup-chromedriver@v2

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Mocha tests
        run: npm test
