name: Mocha

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      [opened, reopened, edited, ready_for_review, synchronize]
    branches:
      - 'main'
      - 'release/**'

jobs:
  test:
    name: Run mocha
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - "4444:4444"
        options: --shm-size="2g"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      - name: Install dependencies
        run: npm i

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Build
        run: npm run build

      - name: Start React app
        run: |
          npm start &

      - name: Wait for React app to be ready
        run: |
          wait-on http://localhost:3000

      - name: Run tests
        run: npm run test

